AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  API for Yer-Song App

Parameters:
  DynamoDbEndpoint:
    Description: The url prefix requests to the song api
    Type: String
    Default: http://host.docker.internal:4566
  AllowOrigin:
    Description: The origin the server allows for CORS purposes
    Type: String
    Default: "'http://localhost:3001'"

Globals:
  Function:
    Timeout: 10

Resources:
  SongByIdAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "Prod"
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowOrigin: !Ref AllowOrigin
        AllowHeaders: "'Content-Type'"

  SongByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          API_ENDPOINT: !Ref DynamoDbEndpoint
      CodeUri: songs/
      Handler: app.getSong
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        Song:
          Type: Api
          Properties:
            Path: /songs/{id}
            Method: get
            RestApiId: !Ref SongByIdAPI
      Policies: AWSLambdaDynamoDBExecutionRole
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
    Connectors:
      ReadFromSongs:
        Properties:
          Destination:
            Id: SongTable
          Permissions:
            - Read
  SongTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: song
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SongByIdAPI:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${SongByIdAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  SongByIdFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt SongByIdFunction.Arn
  SongByIdFunctionFunctionIamRole:
    Description: "Implicit IAM Role"
    Value: !GetAtt SongByIdFunctionRole.Arn
